### ISSUE TITLE
Error Layout when scrolling page

### ISSUE THREAD

**Issue by rendramhardika** [putraxor/flutter_multipage_form#2]
Hai, Thanks for developed this widget. I've got some issues.
I trying to create many forms with that flying action button. When there are many forms, i've got some error with error message like this.

I/flutter ( 8278): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 8278): The following assertion was thrown during performLayout():
I/flutter ( 8278): FlutterError contained multiple error summaries.
I/flutter ( 8278): All FlutterError objects should have only a single short (one line) summary description of the
I/flutter ( 8278): problem that was detected.
I/flutter ( 8278): Malformed FlutterError:
I/flutter ( 8278):   RenderCustomSingleChildLayoutBox object was given an infinite size during layout.
I/flutter ( 8278):   This probably means that it is a render object that tries to be as big as possible, but it was put
I/flutter ( 8278):   inside another render object that allows its children to pick their own size.
I/flutter ( 8278):   RenderCustomSingleChildLayoutBox object was given an infinite size during layout.
I/flutter ( 8278):   This probably means that it is a render object that tries to be as big as possible, but it was put
I/flutter ( 8278):   inside another render object that allows its children to pick their own size.
I/flutter ( 8278):   The nearest ancestor providing an unbounded width constraint is: RenderIndexedSemantics#80493 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter ( 8278):     creator: IndexedSemantics ← NotificationListener<KeepAliveNotification> ← KeepAlive ←
I/flutter ( 8278):       AutomaticKeepAlive ← KeyedSubtree ← SliverList ← MediaQuery ← SliverPadding ← Viewport ←
I/flutter ( 8278):       IgnorePointer-[GlobalKey#935c1] ← Semantics ← Listener ← ⋯
I/flutter ( 8278):     parentData: index=0; layoutOffset=0.0 (can use size)
I/flutter ( 8278):     constraints: BoxConstraints(0.0<=w<=Infinity, h=720.1)
I/flutter ( 8278):     semantic boundary
I/flutter ( 8278):     size: MISSING
I/flutter ( 8278):     index: 0
I/flutter ( 8278):   The nearest ancestor providing an unbounded height constraint is: RenderFlex#9aa63 relayoutBoundary=up9 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:       
I/flutter ( 8278):     creator: Column ← _FormScope ← WillPopScope ← Form-[LabeledGlobalKey<FormState>#61519] ←
I/flutter ( 8278):       DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#f9aa0 ink renderer] ←
I/flutter ( 8278):       NotificationListener<LayoutChangedNotification> ← CustomPaint ← _ShapeBorderPaint ← PhysicalShape
I/flutter ( 8278):       ← _MaterialInterior ← ⋯
I/flutter ( 8278):     parentData: <none> (can use size)
I/flutter ( 8278):     constraints: BoxConstraints(0.0<=w<=Infinity, h=688.1)
I/flutter ( 8278):     size: MISSING
I/flutter ( 8278):     direction: vertical
I/flutter ( 8278):     mainAxisAlignment: start
I/flutter ( 8278):     mainAxisSize: min
I/flutter ( 8278):     crossAxisAlignment: center
I/flutter ( 8278):     verticalDirection: down
I/flutter ( 8278):   The constraints that applied to the RenderCustomSingleChildLayoutBox were:
I/flutter ( 8278):     BoxConstraints(unconstrained)
I/flutter ( 8278):   The exact size it was given was:
I/flutter ( 8278):     Size(Infinity, 56.0)
I/flutter ( 8278):   See https://flutter.dev/docs/development/ui/layout/box-constraints for more information.
I/flutter ( 8278):
I/flutter ( 8278): The malformed error has 2 summaries.
I/flutter ( 8278): Summary 1: RenderCustomSingleChildLayoutBox object was given an infinite size during layout.
I/flutter ( 8278): Summary 2: RenderCustomSingleChildLayoutBox object was given an infinite size during layout.
I/flutter ( 8278): 
I/flutter ( 8278): This error should still help you solve your problem, however please also report this malformed error
I/flutter ( 8278): in the framework by filing a bug on GitHub:
I/flutter ( 8278):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 8278):
I/flutter ( 8278): When the exception was thrown, this was the stack:
I/flutter ( 8278): #0      new FlutterError.fromParts.<anonymous closure> (package:flutter/src/foundation/assertions.dart:540:9)
I/flutter ( 8278): #1      new FlutterError.fromParts (package:flutter/src/foundation/assertions.dart:543:6)
I/flutter ( 8278): #2      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1966:28)
I/flutter ( 8278): #3      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:2029:6)
I/flutter ( 8278): #4      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1740:7)
I/flutter ( 8278): #5      RenderBox.size= (package:flutter/src/rendering/box.dart:1742:6)
I/flutter ( 8278): #6      RenderCustomSingleChildLayoutBox.performLayout (package:flutter/src/rendering/shifted_box.dart:1118:5)
I/flutter ( 8278): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8278): #9      _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
I/flutter ( 8278): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #11     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
I/flutter ( 8278): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #13     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:392:13)
I/flutter ( 8278): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8278): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8278): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8278): #20     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
I/flutter ( 8278): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8278): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8278): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #26     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:743:15)
I/flutter ( 8278): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8278): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8278): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8278): #33     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
I/flutter ( 8278): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #35     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
I/flutter ( 8278): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8278): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8278): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #41     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:165:27)
I/flutter ( 8278): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #43     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
I/flutter ( 8278): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #45     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
I/flutter ( 8278): #46     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1334:12)
I/flutter ( 8278): #47     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1252:20)
I/flutter ( 8278): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #49     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8278): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #51     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8278): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #53     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8278): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #55     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8278): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #57     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8278): #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #59     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8278): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8278): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8278): #63     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter ( 8278): #64     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
I/flutter ( 8278): #65     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter ( 8278): #66     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter ( 8278): #67     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
I/flutter ( 8278): #68     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter ( 8278): #69     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter ( 8278): #70     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 8278): #71     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter ( 8278): #72     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)    
I/flutter ( 8278): #73     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter ( 8278): #74     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter ( 8278): #78     _invoke (dart:ui/hooks.dart:236:10)
I/flutter ( 8278): #79     _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter ( 8278): (elided 3 frames from package dart:async)
I/flutter ( 8278):
I/flutter ( 8278): The following RenderObject was being processed when the exception was fired: RenderCustomSingleChildLayoutBox#3b626 relayoutBoundary=up18 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter ( 8278):   creator: CustomSingleChildLayout ← ClipRect ← MediaQuery ← Padding ← SafeArea ← Align ← Semantics ←
I/flutter ( 8278):     DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#9fad1 ink renderer] ←
I/flutter ( 8278):     NotificationListener<LayoutChangedNotification> ← PhysicalModel ← ⋯
I/flutter ( 8278):   parentData: <none> (can use size)
I/flutter ( 8278):   constraints: BoxConstraints(unconstrained)
I/flutter ( 8278):   size: Size(Infinity, 56.0)
I/flutter ( 8278): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#7eb44 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 8278): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 549 pos 12: 'child.hasSize': is not true.
I/flutter ( 8278): Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
I/flutter ( 8278): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter ( 8278): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.

here the screenshot from this error.
![Screenshot_20190826-163440](https://user-images.githubusercontent.com/43908428/63681268-a936e800-c81f-11e9-8e85-b39a5b85b0d2.png)

hope that you can help me..
thanks

**Comment by solution-odii** [comment]
I have the same error too, any solution yet??/

**Comment by rendramhardika** [comment]
Nope. I've changed my UI because there is no solution come.

**Comment by solution-odii** [comment]
Okay thanks... I'll still check if I can get a fix, and I'll update you

**Comment by maniecodes** [comment]
having the same error

**Comment by krishnashetty0** [comment]
I am getting this error. 
It happens when I add more that one forms and try to scroll up and down. Any hints?

**Comment by krishnashetty0** [comment]
Opened this SO https://stackoverflow.com/questions/62035839/listview-crashes-list-of-statefulwidgets

**Comment by Basyir91** [comment]
Has anyone found any solutions?

I just want to share my solution: In form.dart:

line 8: delete final state = _UserFormState();

line 13: replace
_UserFormState createState() => _UserFormState();
bool isValid() => _UserFormState().validate();

**Comment by girishrajgopal-td** [comment]
> Has anyone found any solutions?
> 
> I just want to share my solution: In form.dart:
> 
> line 8: delete final state = _UserFormState();
> 
> line 13: replace
> _UserFormState createState() => _UserFormState();
> bool isValid() => _UserFormState().validate();

this doesnt work. validate functions return empty!.

**Comment by JAYAMURUGANJ** [comment]
inside the multiform page using the ListView inside the SingleChildScroolView

it was working for me


SingleChildScrollView(
                child: ListView.builder(
                  physics: NeverScrollableScrollPhysics(),
                  shrinkWrap: true,
                  scrollDirection: Axis.vertical,
                  addAutomaticKeepAlives: true,
                  itemCount: products.length,
                  itemBuilder: (_, i) => products[i],
                ),
              ),
